### ISSUE TITLE
[Feature Request]: play result in browser

### ISSUE THREAD

**Issue by ClashSAN** [enlyth/sd-webui-riffusion#2]
Is it trivial, or bit difficult to add an audio player?

this extension has a hack to add microphone and audio playback functions: https://github.com/152334H/sd-webui-whisper

It looks like you've put latent space interpolation as a to-do. can't wait . !🚀

**Comment by enlyth** [comment]
Check the latest version on master, I have added a button that displays inline audio players for the last batch. Still not ideal, but I feel a bit limited by Gradio and the way the UI is handled in extensions

**Comment by ClashSAN** [comment]
didn't see that, my bad
