### ISSUE TITLE
Batch img2img? 

### ISSUE THREAD

**Issue by aavetis** [enlyth/sd-webui-riffusion#4]
if we use Batch Img2Img and specify a folder with multiple 5 second spectrograms, how can we make multiple 5 second wav clips (either combined or separate)? 

riffusion.py seems to have zombie code in there, can't tell if that functionality is there or expected to work

**Comment by enlyth** [comment]
I have added this functionality in the latest version (you can specify a folder manually in the Riffusion tab, and convert all audio to individual plus optionally a joined wav file)
